scan_filter_chain:
        - name: box_filter
          type: laser_filters/LaserScanBoxFilter
          params:
                  box_frame: robot1/base_footprint
                  min_x: -0.12 
                  max_x: 0.12
                  min_y: -0.12
                  max_y: 0.12
                  min_z: -0.2
                  max_z: 0.2

tf_message_filter_tolerance: 0.6